# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: maven:3.8.5-openjdk-11

pipelines:
  default:
    - parallel:
        - step:
            name: 'Run karate Tests'
            caches:
              - maven  # Caches Maven dependencies
            script:
              - mvn clean install
              - mvn test -Dkarate.options="--tags @UPI_BASIC_check1"
            #              - mvn test -Dtest=GeneralTestRunner

        - step:
            name: "Publish Test Results"
            script:
              - pipe: atlassian/pytest-test-results:0.1.0
                variables:
                  TEST_RESULTS: '**/target/test-*.xml'

            artifacts:
              - target/karate-reports/**
definitions:
  caches:
    maven: ~/.m2/repository  # Cache for Maven dependencies
    
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    #- step:
    #    name: 'Deployment to Staging'
    #    deployment: staging
    #    script:
    #      - echo "Your deployment to staging script goes here..."
    #- step:
    #    name: 'Deployment to Production'
    #    deployment: production
    #    trigger: 'manual'
    #    script:
    #      - echo "Your deployment to production script goes here..."
