# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: maven:3.8.5-openjdk-17

pipelines:
  custom:
    Test_Env_Insights_Verification:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Test_Env_Insights_Verification"
            - mvn test -Dkarate.env=test-fidoV2 -Dkarate.options="--threads 5  --tags ~@ignore"  -Dtest=MonnaiTestRunner#testInsightsVerification
          artifacts:
            - target/karate-reports/**

    Test_Env_Insights:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Test_Env_Insights"
            - mvn test -Dkarate.env=release-fidoV2 -Dkarate.options="--threads 5  --tags ~@ignore" -Dtest=MonnaiTestRunner#testInsights
          artifacts:
            - target/karate-reports/**

    Test_Env_Verification:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Date and Day ..... "
            - DATE_TIME=$(TZ="Asia/Kolkata" date '+%d-%m-%Y_%H-%M-%S')
            - DATE=$(TZ="Asia/Kolkata" date '+%d-%m-%Y')
            - TIME=$(TZ="Asia/Kolkata" date '+%H:%M:%S')
            - echo "$DATE_TIME"
            # Install Aws CLI for uploading artifacts to S3
            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            - unzip awscliv2.zip && ./aws/install
            - rm -rf awscliv2.zip aws
            - aws --version
            # Generate Allure Report
            - echo "Generating Report."
            - allure generate allure-results --clean -o allure-report --single-file
            - aws s3 cp allure-report/** s3://autoreports/$DATE_TIME/
            - Report_Url="https://autoreports.s3.ap-southeast-1.amazonaws.com/$DATE_TIME/index.html"
            # Run report
            - echo "Running Karate tests - Test_Env_Verification"
            - mvn test -Dkarate.env=release-fidoV2 -Dkarate.options="--threads 5  --tags ~@ignore" -Dtest=MonnaiTestRunner#testVerification
          artifacts:
            - target/karate-reports/**

    Release_Env_Insights_Verification:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Release_Env_Insights_Verification"
            - mvn clean test -Dkarate.env=release-fidoV2 -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#testInsightsVerification
          artifacts:
            - target/karate-reports/**

    Release_Env_Insights:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Release_Env_Insights"
            - mvn clean test -Dkarate.env=release-fidoV2 -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#testInsights
          artifacts:
            - target/karate-reports/**

    Release_Env_Verification:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            script:
            - echo "Running Karate tests - Release_Env_Verification"
            - mvn clean test -Dkarate.env=release-fidoV2 -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#testVerification
          artifacts:
            - target/karate-reports/**

    Dev_Env_Insights_Verification:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Dev_Env_Insights_Verification"
            - mvn clean test -Dkarate.env=dev-m -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#testInsightsVerification
          artifacts:
            - target/karate-reports/**

    Dev_Env_Insights:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Dev_Env_Insights"
            - mvn clean test -Dkarate.env=dev-m -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#testInsights
          artifacts:
            - target/karate-reports/**

    Dev_Env_Verification:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Dev_Env_Verification"
            - mvn clean test -Dkarate.env=dev-m -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#testVerification
          artifacts:
            - target/karate-reports/**

    Test_Env_authGen:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            - echo "Running Karate tests - Test_Env_authGen"
            - mvn test -Dkarate.env=test-fidoV2 -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#auth_Token
          artifacts:
            - target/karate-reports/**

    Release_Env_authGen:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            # Run report
            - echo "Running Karate tests - Release_Env_authGen"
            - mvn test -Dkarate.env=release-fidoV2 -Dkarate.options="--threads 5 --tags ~@ignore" -Dtest=MonnaiTestRunner#auth_Token
          artifacts:
            - target/karate-reports/**

      - step:
          name: Generate Report - Release_Env_authGen
          script:
            - echo "Date and Day ..... "
            - DATE_TIME=$(TZ="Asia/Kolkata" date '+%d-%m-%Y_%H-%M-%S')
            - DATE=$(TZ="Asia/Kolkata" date '+%d-%m-%Y')
            - TIME=$(TZ="Asia/Kolkata" date '+%H:%M:%S')
            - echo "$DATE_TIME"
            # Install Aws CLI for uploading artifacts to S3
            - set -e
            - echo "Installing AWS CLI..."
#              # Install Homebrew using the official script
              if ! command -v brew &> /dev/null; then
              echo "Homebrew is not installed. Installing Homebrew..."
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              fi
            - brew install curl unzip

              #            - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#            - brew install curl unzip
#            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#            - apt-get install -y unzip
#            - unzip awscliv2.zip
#            - sudo ./aws/install
#            - aws --version
             # Install Aws CLI for uploading artifacts to S3
            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            - unzip awscliv2.zip && ./aws/install
            - rm -rf awscliv2.zip aws
            - aws --version

            - echo "Coping Karate Report to S3"
              # Upload to S3
            - echo "Uploading Karate report to S3..."
            - aws s3 cp target/karate-reports/karate-summary.html s3://autokaratereport/karate-reports/report.html --acl public-read
#            - aws s3 cp ${REPORT_DIR}/karate-summary.html s3://${S3_BUCKET_NAME}/${S3_REPORT_PATH} --acl public-read
#            - aws s3 cp target/karate-reports/** s3://autokaratereport/$DATE_TIME/
            - Report_Url="https://autokaratereport.s3.ap-southeast-1.amazonaws.com/$DATE_TIME/index.html"
            - Slack_Url="https://hooks.slack.com/services/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"
            - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"Here is the Automation karate Report for DPI Regression Suite on $DATE at $TIME\n $Report_Url\"}" $Slack_Url'

          artifacts:
            - target/karate-results/**



