# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: maven:3.8.5-openjdk-17

pipelines:
  custom:
    Run_sample_karate_file:
      - step:
          name: Run Karate Tests
          caches:
            - maven
          script:
            # Install Maven
            - echo "Running Karate tests..."
            - mvn clean test -Dtest=DemoRunner#auth_Token
          artifacts:
            - target/karate-reports/**

