Feature: general

  Background:
    * configure charset = null
    #   * def authFeature = call read('classpath:monnai/Auth_Token_Generation.feature')
    * def BearerToken = "Bearer eyJraWQiOiJUeHZBRldSUTJ4QVJjSGlVeVRtQisyV3BKa3VLaTZ3aDZKbkNaXC9nNkJBYz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1ODM3ZjIzZS1kNGUwLTRiOTktOTU0Ni05OTUyYjYwMDllMmIiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTFfdFhFUlFkZTdGIiwidmVyc2lvbiI6MiwiY2xpZW50X2lkIjoiMmhscDRndTRlYTRrMG9qczhoaHFxc28xZmQiLCJvcmlnaW5fanRpIjoiZWEzNTM1ZDAtZDg3NS00NzgxLThlMTQtMDI2OGMzMzgyODA1IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJwaG9uZSBvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImF1dGhfdGltZSI6MTcwMTI0NzQyNiwiZXhwIjoxNzAxMzMzODI2LCJpYXQiOjE3MDEyNDc0MjcsImp0aSI6ImI3NTNmN2QwLWMyNDMtNGM3OC05YWI4LThjOTUxZmRmNTAxYiIsInVzZXJuYW1lIjoiNTgzN2YyM2UtZDRlMC00Yjk5LTk1NDYtOTk1MmI2MDA5ZTJiIn0.RAfwRnO0tSZtlES2n4NuQdEF3OdcQG_nhEK0inuwIlS3TGfN724oTd59FKv4l2OgWWAMW6gmUWL9pOmSwNNpnzFhNovmOcJiWyLmWU62pQtvtmSImrfkxYe7RtKn8UBxbVNDe_wFkzJ9dEYyvLa-kI_S2Hw5snxze_roLH6MG0ahWEGlVMJGVVvUWcbocknEvtUWRS942WYNMS9yh76oqHziHV6Eje1VazrASlc3sRjw8SqqQ7X41uoxRORq8ZBIiZE5SEIOHE-n2g2_7vCpJ4qtFYYkMaiDk1Ga4OwzUjYPK3FuRd1qQ8CwkKilcfhp_sOSdZ-cyk7-2xrVk0d3sw"

  Scenario:GET required data from file
    And def payloadGenJSON = read("Samples/sample_general.json")
    * print 'payloadGenJSON--->',payloadGenJSON
    * def required = get payloadGenJSON.data[*].id
    * print 'required--->',required